class AddColumn < ActiveRecord::Migration[5.2]
  def change
  	add_column :encuesta, :pregunta1, :string
  	add_column :encuesta, :pregunta2, :string
  	add_column :encuesta, :pregunta1A, :string
  	add_column :encuesta, :pregunta2A, :string
  	add_column :encuesta, :pregunta2B, :string
  	add_column :encuesta, :pregunta3, :string
  	add_column :encuesta, :pregunta4, :string
  	add_column :encuesta, :pregunta5, :string
  	add_column :encuesta, :pregunta5A, :string
  	add_column :encuesta, :pregunta6, :string
  	add_column :encuesta, :pregunta7A, :string
  	add_column :encuesta, :pregunta7B, :string
  	add_column :encuesta, :pregunta7C, :string
  	add_column :encuesta, :pregunta7D, :string
  	add_column :encuesta, :pregunta7E, :string
  	add_column :encuesta, :pregunta7F, :string
  	add_column :encuesta, :pregunta7G, :string
  	add_column :encuesta, :pregunta7H, :string
  	add_column :encuesta, :pregunta7I, :string
  	add_column :encuesta, :pregunta7J, :string
  	add_column :encuesta, :pregunta7K, :string
  	add_column :encuesta, :pregunta7L, :string
  	add_column :encuesta, :pregunta7M, :string
  	add_column :encuesta, :pregunta7N, :string


  	add_column :encuesta, :pregunta8A, :string
  	add_column :encuesta, :pregunta8B, :string
  	add_column :encuesta, :pregunta8C, :string
  	add_column :encuesta, :pregunta8D, :string
  	add_column :encuesta, :pregunta8E, :string
  	add_column :encuesta, :pregunta8F, :string
  	add_column :encuesta, :pregunta8G, :string
    
  	add_column :encuesta, :pregunta9A, :string
  	add_column :encuesta, :pregunta9B, :string
  	add_column :encuesta, :pregunta9C, :string
  	add_column :encuesta, :pregunta9D, :string
  	add_column :encuesta, :pregunta9E, :string
  	add_column :encuesta, :pregunta9F, :string
  	add_column :encuesta, :pregunta9G, :string

  	  	add_column :encuesta, :pregunta10_a, :string
  	add_column :encuesta, :pregunta10_b1, :string
  	add_column :encuesta, :pregunta10_b2, :string
  	add_column :encuesta, :pregunta10_b3, :string
  	add_column :encuesta, :pregunta10_b4, :string
  	add_column :encuesta, :pregunta10_b5, :string
  	add_column :encuesta, :pregunta10_b6, :string
  	add_column :encuesta, :pregunta10_c, :string
  	add_column :encuesta, :pregunta10_d, :string
  	add_column :encuesta, :pregunta10_e, :string
  	add_column :encuesta, :pregunta10_f, :string
  	add_column :encuesta, :pregunta10_g, :string
  	add_column :encuesta, :pregunta10_h, :string
  	add_column :encuesta, :pregunta10_i, :string
  	add_column :encuesta, :pregunta10_j, :string
  	add_column :encuesta, :pregunta10_k, :string
  	add_column :encuesta, :pregunta10_l, :string
  	add_column :encuesta, :pregunta10_m, :string
  	add_column :encuesta, :pregunta10_n, :string

  	add_column :encuesta, :pregunta11_a, :string
  	add_column :encuesta, :pregunta11_b1, :string
  	add_column :encuesta, :pregunta11_b2, :string
  	add_column :encuesta, :pregunta11_b3, :string
  	add_column :encuesta, :pregunta11_b4, :string
  	add_column :encuesta, :pregunta11_b5, :string
  	add_column :encuesta, :pregunta11_b6, :string
  	add_column :encuesta, :pregunta11_c, :string
  	add_column :encuesta, :pregunta11_d, :string
  	add_column :encuesta, :pregunta11_e, :string
  	add_column :encuesta, :pregunta11_f, :string
  	add_column :encuesta, :pregunta11_g, :string
  	add_column :encuesta, :pregunta11_h, :string
  	add_column :encuesta, :pregunta11_i, :string
  	add_column :encuesta, :pregunta11_j, :string
  	add_column :encuesta, :pregunta11_k, :string
  	add_column :encuesta, :pregunta11_l, :string
  	add_column :encuesta, :pregunta11_m, :string
  	add_column :encuesta, :pregunta11_n, :string

  	add_column :encuesta, :pregunta12_a, :string
  	add_column :encuesta, :pregunta12_b1, :string
  	add_column :encuesta, :pregunta12_b2, :string
  	add_column :encuesta, :pregunta12_b3, :string
  	add_column :encuesta, :pregunta12_b4, :string
  	add_column :encuesta, :pregunta12_b5, :string
  	add_column :encuesta, :pregunta12_b6, :string
  	add_column :encuesta, :pregunta12_c, :string
  	add_column :encuesta, :pregunta12_d, :string
  	add_column :encuesta, :pregunta12_e, :string
  	add_column :encuesta, :pregunta12_f, :string
  	add_column :encuesta, :pregunta12_g, :string
  	add_column :encuesta, :pregunta12_h, :string
  	add_column :encuesta, :pregunta12_i, :string
  	add_column :encuesta, :pregunta12_j, :string
  	add_column :encuesta, :pregunta12_k, :string
  	add_column :encuesta, :pregunta12_l, :string
  	add_column :encuesta, :pregunta12_m, :string
  	add_column :encuesta, :pregunta12_n, :string

  	add_column :encuesta, :pregunta13_a, :string
  	add_column :encuesta, :pregunta13_b1, :string
  	add_column :encuesta, :pregunta13_b2, :string
  	add_column :encuesta, :pregunta13_b3, :string
  	add_column :encuesta, :pregunta13_b4, :string
  	add_column :encuesta, :pregunta13_b5, :string
  	add_column :encuesta, :pregunta13_b6, :string
  	add_column :encuesta, :pregunta13_c, :string
  	add_column :encuesta, :pregunta13_d, :string
  	add_column :encuesta, :pregunta13_e, :string
  	add_column :encuesta, :pregunta13_f, :string
  	add_column :encuesta, :pregunta13_g, :string
  	add_column :encuesta, :pregunta13_h, :string
  	add_column :encuesta, :pregunta13_i, :string
  	add_column :encuesta, :pregunta13_j, :string
  	add_column :encuesta, :pregunta13_k, :string
  	add_column :encuesta, :pregunta13_l, :string
  	add_column :encuesta, :pregunta13_m, :string
  	add_column :encuesta, :pregunta13_n, :string

  	add_column :encuesta, :pregunta14, :string
  	add_column :encuesta, :pregunta14_1, :string
  	add_column :encuesta, :pregunta14_otra, :string

  	add_column :encuesta, :pregunta15_a, :string
  	add_column :encuesta, :pregunta15_b, :string
  	add_column :encuesta, :pregunta15_c, :string
  	add_column :encuesta, :pregunta15_d, :string
  	add_column :encuesta, :pregunta15_e, :string
  	add_column :encuesta, :pregunta15_f, :string

  	add_column :encuesta, :pregunta15_A, :string

  	add_column :encuesta, :pregunta16, :string
  	add_column :encuesta, :pregunta16_s1, :string
  	add_column :encuesta, :pregunta16_s2, :string
  	add_column :encuesta, :pregunta16_s3, :string
  	add_column :encuesta, :pregunta16_s4, :string

  	add_column :encuesta, :pregunta17, :string
  	add_column :encuesta, :pregunta17A, :string
  	add_column :encuesta, :pregunta18, :string
  	add_column :encuesta, :pregunta19, :string

  	add_column :encuesta, :pregunta20A_1, :string
  	add_column :encuesta, :pregunta20A_2, :string
  	add_column :encuesta, :pregunta20A_3, :string
  	add_column :encuesta, :pregunta20A_4, :string
  	add_column :encuesta, :pregunta20A_5, :string
  	add_column :encuesta, :pregunta20A_6, :string
  	add_column :encuesta, :pregunta20A_7, :string
  	add_column :encuesta, :pregunta20A_8, :string
  	add_column :encuesta, :pregunta20A_9, :string
  	add_column :encuesta, :pregunta20A_10, :string
  	add_column :encuesta, :pregunta20A_11, :string
  	add_column :encuesta, :pregunta20A_12, :string
  	add_column :encuesta, :pregunta20A_13, :string
  	add_column :encuesta, :pregunta20A_14, :string
  	add_column :encuesta, :pregunta20A_15, :string
  	add_column :encuesta, :pregunta20A_16, :string
  	add_column :encuesta, :pregunta20A_17, :string
  	add_column :encuesta, :pregunta20A_18, :string
  	add_column :encuesta, :pregunta20A_19, :string
  	add_column :encuesta, :pregunta20A_20, :string
  	add_column :encuesta, :pregunta20A_21, :string

   	add_column :encuesta, :pregunta20B_1, :string
  	add_column :encuesta, :pregunta20B_2, :string
  	add_column :encuesta, :pregunta20B_3, :string
  	add_column :encuesta, :pregunta20B_4, :string
  	add_column :encuesta, :pregunta20B_5, :string
  	add_column :encuesta, :pregunta20B_6, :string
  	add_column :encuesta, :pregunta20B_7, :string
  	add_column :encuesta, :pregunta20B_8, :string
  	add_column :encuesta, :pregunta20B_9, :string
  	add_column :encuesta, :pregunta20B_10, :string
  	add_column :encuesta, :pregunta20B_11, :string
  	add_column :encuesta, :pregunta20B_12, :string
  	add_column :encuesta, :pregunta20B_13, :string
  	add_column :encuesta, :pregunta20B_14, :string
  	add_column :encuesta, :pregunta20B_15, :string
  	add_column :encuesta, :pregunta20B_16, :string
  	add_column :encuesta, :pregunta20B_17, :string
  	add_column :encuesta, :pregunta20B_18, :string
  	add_column :encuesta, :pregunta20B_19, :string
  	add_column :encuesta, :pregunta20B_20, :string
  	add_column :encuesta, :pregunta20B_21, :string

   	add_column :encuesta, :pregunta20C_1, :string
  	add_column :encuesta, :pregunta20C_2, :string
  	add_column :encuesta, :pregunta20C_3, :string
  	add_column :encuesta, :pregunta20C_4, :string
  	add_column :encuesta, :pregunta20C_5, :string
  	add_column :encuesta, :pregunta20C_6, :string
  	add_column :encuesta, :pregunta20C_7, :string
  	add_column :encuesta, :pregunta20C_8, :string
  	add_column :encuesta, :pregunta20C_9, :string
  	add_column :encuesta, :pregunta20C_10, :string
  	add_column :encuesta, :pregunta20C_11, :string
  	add_column :encuesta, :pregunta20C_12, :string
  	add_column :encuesta, :pregunta20C_13, :string
  	add_column :encuesta, :pregunta20C_14, :string
  	add_column :encuesta, :pregunta20C_15, :string
  	add_column :encuesta, :pregunta20C_16, :string
  	add_column :encuesta, :pregunta20C_17, :string
  	add_column :encuesta, :pregunta20C_18, :string
  	add_column :encuesta, :pregunta20C_19, :string
  	add_column :encuesta, :pregunta20C_20, :string
  	add_column :encuesta, :pregunta20C_21, :string

   	add_column :encuesta, :pregunta20D_1, :string
  	add_column :encuesta, :pregunta20D_2, :string
  	add_column :encuesta, :pregunta20D_3, :string
  	add_column :encuesta, :pregunta20D_4, :string
  	add_column :encuesta, :pregunta20D_5, :string
  	add_column :encuesta, :pregunta20D_6, :string
  	add_column :encuesta, :pregunta20D_7, :string
  	add_column :encuesta, :pregunta20D_8, :string
  	add_column :encuesta, :pregunta20D_9, :string
  	add_column :encuesta, :pregunta20D_10, :string
  	add_column :encuesta, :pregunta20D_11, :string
  	add_column :encuesta, :pregunta20D_12, :string
  	add_column :encuesta, :pregunta20D_13, :string
  	add_column :encuesta, :pregunta20D_14, :string
  	add_column :encuesta, :pregunta20D_15, :string
  	add_column :encuesta, :pregunta20D_16, :string
  	add_column :encuesta, :pregunta20D_17, :string
  	add_column :encuesta, :pregunta20D_18, :string
  	add_column :encuesta, :pregunta20D_19, :string
  	add_column :encuesta, :pregunta20D_20, :string
  	add_column :encuesta, :pregunta20D_21, :string

    add_column :encuesta, :pregunta20E_1, :string
  	add_column :encuesta, :pregunta20E_2, :string
  	add_column :encuesta, :pregunta20E_3, :string
  	add_column :encuesta, :pregunta20E_4, :string
  	add_column :encuesta, :pregunta20E_5, :string
  	add_column :encuesta, :pregunta20E_6, :string
  	add_column :encuesta, :pregunta20E_7, :string
  	add_column :encuesta, :pregunta20E_8, :string
  	add_column :encuesta, :pregunta20E_9, :string
  	add_column :encuesta, :pregunta20E_10, :string
  	add_column :encuesta, :pregunta20E_11, :string
  	add_column :encuesta, :pregunta20E_12, :string
  	add_column :encuesta, :pregunta20E_13, :string
  	add_column :encuesta, :pregunta20E_14, :string
  	add_column :encuesta, :pregunta20E_15, :string
  	add_column :encuesta, :pregunta20E_16, :string
  	add_column :encuesta, :pregunta20E_17, :string
  	add_column :encuesta, :pregunta20E_18, :string
  	add_column :encuesta, :pregunta20E_19, :string
  	add_column :encuesta, :pregunta20E_20, :string
  	add_column :encuesta, :pregunta20E_21, :string

  	add_column :encuesta, :pregunta20F_1, :string
  	add_column :encuesta, :pregunta20F_2, :string
  	add_column :encuesta, :pregunta20F_3, :string
  	add_column :encuesta, :pregunta20F_4, :string
  	add_column :encuesta, :pregunta20F_5, :string
  	add_column :encuesta, :pregunta20F_6, :string
  	add_column :encuesta, :pregunta20F_7, :string
  	add_column :encuesta, :pregunta20F_8, :string
  	add_column :encuesta, :pregunta20F_9, :string
  	add_column :encuesta, :pregunta20F_10, :string
  	add_column :encuesta, :pregunta20F_11, :string
  	add_column :encuesta, :pregunta20F_12, :string
  	add_column :encuesta, :pregunta20F_13, :string
  	add_column :encuesta, :pregunta20F_14, :string
  	add_column :encuesta, :pregunta20F_15, :string
  	add_column :encuesta, :pregunta20F_16, :string
  	add_column :encuesta, :pregunta20F_17, :string
  	add_column :encuesta, :pregunta20F_18, :string
  	add_column :encuesta, :pregunta20F_19, :string
  	add_column :encuesta, :pregunta20F_20, :string
  	add_column :encuesta, :pregunta20F_21, :string

add_column :encuesta, :pregunta21, :string
  	add_column :encuesta, :pregunta21_otra, :string
  	add_column :encuesta, :pregunta22, :string 
  	add_column :encuesta, :pregunta22_otra, :string 
  	add_column :encuesta, :pregunta23, :string 
  	add_column :encuesta, :pregunta24_AA, :string
  	add_column :encuesta, :pregunta24_BB, :string
  	add_column :encuesta, :pregunta25_AA, :string
  	add_column :encuesta, :pregunta25_BB, :string
  	add_column :encuesta, :pregunta26_AA, :string
  	add_column :encuesta, :pregunta26_BB, :string

  	add_column :encuesta, :pregunta27_a, :string
  	add_column :encuesta, :pregunta27_b, :string
  	add_column :encuesta, :pregunta27_c, :string
  	add_column :encuesta, :pregunta27_d, :string
  	add_column :encuesta, :pregunta27_e, :string
  	add_column :encuesta, :pregunta27_f, :string
  	add_column :encuesta, :pregunta27_g, :string
  	add_column :encuesta, :pregunta27_h, :string
  	add_column :encuesta, :pregunta27_j, :string
  	add_column :encuesta, :pregunta27_k, :string

  	add_column :encuesta, :pregunta28_a, :string
  	add_column :encuesta, :pregunta28_b, :string
  	add_column :encuesta, :pregunta28_c, :string
  	add_column :encuesta, :pregunta28_d, :string
  	add_column :encuesta, :pregunta28_e, :string
  	add_column :encuesta, :pregunta28_f, :string
  	add_column :encuesta, :pregunta28_g, :string
  	add_column :encuesta, :pregunta28_h, :string
  	add_column :encuesta, :pregunta28_j, :string
  	add_column :encuesta, :pregunta28_k, :string

  	add_column :encuesta, :pregunta29_a, :string
  	add_column :encuesta, :pregunta29_b, :string

  	add_column :encuesta, :pregunta30, :string

  	add_column :encuesta, :pregunta31_a, :string
  	add_column :encuesta, :pregunta31_b, :string

   	add_column :encuesta, :pregunta32_a, :string
  	add_column :encuesta, :pregunta32_b, :string
  	add_column :encuesta, :pregunta32_c, :string
  	add_column :encuesta, :pregunta32_d, :string

  	add_column :encuesta, :pregunta33, :string
  	add_column :encuesta, :pregunta34, :string
  	add_column :encuesta, :pregunta35, :string
  	add_column :encuesta, :pregunta36, :string
  	add_column :encuesta, :pregunta37, :string
  	add_column :encuesta, :pregunta38, :string
  	add_column :encuesta, :pregunta39, :string
  	add_column :encuesta, :pregunta40, :string
  	add_column :encuesta, :pregunta41, :string
  	add_column :encuesta, :pregunta42, :string
  	add_column :encuesta, :pregunta42_otra, :string
  	add_column :encuesta, :pregunta43, :string
  	add_column :encuesta, :pregunta43_otra, :string
  	add_column :encuesta, :pregunta44, :string
  	add_column :encuesta, :pregunta45, :string
  	add_column :encuesta, :pregunta46, :string
  	add_column :encuesta, :pregunta46_otro, :string
  	add_column :encuesta, :pregunta47, :string
  	add_column :encuesta, :pregunta47_otro, :string
  	add_column :encuesta, :pregunta48, :string
  	add_column :encuesta, :pregunta49, :string
  	add_column :encuesta, :pregunta50, :string
  	add_column :encuesta, :pregunta51, :string
  	add_column :encuesta, :pregunta52, :string
  	add_column :encuesta, :pregunta53, :string
  	add_column :encuesta, :pregunta54, :string
  	add_column :encuesta, :pregunta55, :string
  	add_column :encuesta, :pregunta56, :string
  	add_column :encuesta, :pregunta57, :string
  	add_column :encuesta, :pregunta58, :string
  	add_column :encuesta, :pregunta59, :string
  	add_column :encuesta, :pregunta60, :string

   	add_column :encuesta, :direccion, :string
  	add_column :encuesta, :hora_final, :string
  	add_column :encuesta, :telefono, :string
  	add_column :encuesta, :nombre_encuestador, :string
  	add_column :encuesta, :nombre_supervisor, :string
  	add_column :encuesta, :nombre_coordinador, :string
  	add_column :encuesta, :cedula_encuestador, :string
  	add_column :encuesta, :cedula_supervisor, :string
  	add_column :encuesta, :cedula_coordinador, :string

  	add_column :encuesta, :departamento, :string
  	add_column :encuesta, :municipio, :string
  	add_column :encuesta, :zona, :string
  	add_column :encuesta, :fecha, :string
  	add_column :encuesta, :hora_inicial, :string
  	add_column :encuesta, :nombre_encuestado, :string
  	add_column :encuesta, :sexo, :string
  	add_column :encuesta, :años, :string
  	add_column :encuesta, :F1, :string
  	add_column :encuesta, :F1A, :string
  	add_column :encuesta, :F2, :string
   	add_column :encuesta, :F3_a, :string
   	add_column :encuesta, :F3_b, :string
   	add_column :encuesta, :F3_c, :string
   	add_column :encuesta, :F3_d, :string
   	add_column :encuesta, :F3_e, :string
  	add_column :encuesta, :pregunta20B_1_otra, :string
  	add_column :encuesta, :pregunta20B_2_otra, :string
  	add_column :encuesta, :pregunta20B_3_otra, :string
  	add_column :encuesta, :pregunta20B_4_otra, :string
  	add_column :encuesta, :pregunta20B_5_otra, :string
  	add_column :encuesta, :pregunta20B_6_otra, :string
  	add_column :encuesta, :pregunta20B_7_otra, :string
  	add_column :encuesta, :pregunta20B_8_otra, :string
  	add_column :encuesta, :pregunta20B_9_otra, :string
  	add_column :encuesta, :pregunta20B_10_otra, :string
  	add_column :encuesta, :pregunta20B_11_otra, :string
  	add_column :encuesta, :pregunta20B_12_otra, :string
  	add_column :encuesta, :pregunta20B_13_otra, :string
  	add_column :encuesta, :pregunta20B_14_otra, :string
  	add_column :encuesta, :pregunta20B_15_otra, :string
  	add_column :encuesta, :pregunta20B_16_otra, :string
  	add_column :encuesta, :pregunta20B_17_otra, :string
  	add_column :encuesta, :pregunta20B_18_otra, :string
  	add_column :encuesta, :pregunta20B_19_otra, :string
  	add_column :encuesta, :pregunta20B_20_otra, :string
  	add_column :encuesta, :pregunta20B_21_otra, :string
  	add_column :encuesta, :pregunta27_i, :string
  	add_column :encuesta, :pregunta28_i, :string
  	add_column :encuesta, :pregunta36_otra, :string
  end
end
